### ISSUE TITLE
Change `np.int` to `int`

### ISSUE THREAD

**Issue by Dead-fisher** [BrooksResearchGroup-UM/FastMBAR#3]
Hi,

The code below uses `num_conf = self.num_conf.astype(np.int)` which is deprecated by numpy and may rasie an error. 
Change to `int` will work fine!
 
https://github.com/BrooksResearchGroup-UM/FastMBAR/blob/87bc21f4ad86199eea89af48e0140bc9e3ef7654/FastMBAR/fastmbar.py#L555C37-L555C37

Thanks!

**Comment by xqding** [comment]
Thanks. It is now fixed in the new release.
